Feature: insert issue reference on <CR>
nvim-telescope/telescope-github.nvim pull request #33
Opened 2022-01-03 14:46 UTC by cljoly

Currently, `<CR>` is set to “close Telescope”. There is already a
generic “cancel” mapping for that. I find more useful to just insert the
selected issue in the buffer we come from.

This allows to insert references to GitHub issues in commit messages,
code comments…

2022-01-10 11:22 UTC, sbulav commented
Hi @cljoly 

I agree that it would be more convenient.
I've merged my fork with a lot of changes so please resolve conflicts before I can merge your PR.

2022-01-11 20:50 UTC, cljoly commented
Hi @sbulav , I'll look into reading and fixing conflicts in the next few days. Thanks for your work on this project!

2022-01-14 20:56 UTC, cljoly commented
Alright, it works on my computer, this should be ready if you wanna give it a try.

2022-01-17 07:29 UTC, sbulav requested changes
Overall looks good, but please stick with the same approach for inserting text as we use for other actions.

2022-01-17 07:29 UTC, sbulav commented on lua/telescope/_extensions/gh_actions.lua
> +  vim.cmd("normal! a#" .. issue_number)
Please replace it with:
```
	if vim.api.nvim_buf_get_option(vim.api.nvim_get_current_buf(), "modifiable") then
		vim.api.nvim_put({ issue_number }, "b", true, true)
	end
```

2022-01-17 22:37 UTC, cljoly commented on lua/telescope/_extensions/gh_actions.lua
> +  vim.cmd("normal! a#" .. issue_number)
Should be fixed now.

2022-01-18 15:44 UTC, merged

2022-01-19 06:42 UTC, cljoly commented
Awesome, thanks!